version: 2.1
orbs:
  node: circleci/node@1.1.6

defaults: &defaults
  working_directory: ~/commentor
  executor:
    name: node/default
    tag: "10.4"

commands:
  frontend-test:
    description: "Launching front end unit test"
    steps:
      - run: yarn test:frontend
  frontend-type:
    description: "Launching typecheck on frontend"
    steps:
      - run: yarn type:frontend
  frontend-lint:
    description: "Launching linter check onf frontend"
    steps:
      - run: yarn quality:frontend

jobs:
  install-front:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "frontend/package.json" }}
            - node-modules-cache-
      - run: yarn install:frontend
      - save_cache:
          key: node-modules-cache-{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules
      - persist_to_workspace:
          root: ~/commentor
          paths:
            - frontend/node_modules
  test-frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "frontend/package.json" }}
            - node-modules-cache-
      - frontend-test
  type-frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "frontend/package.json" }}
            - node-modules-cache-
      - frontend-type
  quality-frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "frontend/package.json" }}
            - node-modules-cache-
      - frontend-type

workflows:
  version: 2
  checks-front:
    jobs:
      - install-front
      - test-frontend:
          requires:
            - install-front
      - type-frontend:
          requires:
            - install-front
      - quality-frontend:
          requires:
            - install-front
